---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboss-server
  namespace: java
  labels:
    app: jbossapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jbossapi
  template:
    metadata:
      labels:
        app: jbossapi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: jbossapi
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: jboss-service
  namespace: java
spec:
  selector:
    app: jbossapi
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: java
  name: jboss-ingress
  annotations:
    allow.http: "false"
spec:
  rules:
  - host: wildfly.prod.globaltranscribe.com
    http:
      paths:
        - path: /
          backend:
            serviceName: jboss-service
            servicePort: 80